image: nvcr.io/isse/pyh5db:3.7-extended.v3

stages:
  - lint
  - test

linter:
  stage: lint
  script:
    - pip install prettytable
    - flake8 --max-line-length=120 --ignore=W291,W503,W504 --exclude=Debugging,Legacy .

test:
  stage: test
  script:
    - python3 -m unittest discover -s Tests -t Tests

#  only:
#    - master