image: nvcr.io/isse/pytorch_extended:19.12

stages:
  - lint
  - test
  - docs

linter:
  stage: lint
  script:
    - flake8 --max-line-length=120 --ignore=W291,W503,W504 .

test:
  stage: test
  script:
    - python3 -m unittest discover -s Tests -t Tests
  tags:
    - dgx2

  only:
    - master

documentation: 
  stage: docs 
  script:
    - pip install -U sphinx
    - cd ./Docs
    - make html 
  artifacts:
    paths
    - ./Docs/build/html
  #only:
  #  - master 
