image: nvcr.io/isse/pytorch_extended:19.07

stages:
  - lint
  - test

linter:
  stage: lint
  script:
    - flake8 --max-line-length=120 --ignore=W291,W503,W504 --exclude=Debugging,Legacy .

test:
  stage: test
  script:
    #    - ls /cfs/home
    - python3 -m unittest discover -s Tests -t Tests
  # - python3 -m unittest Tests.test_eval.TestEval

  only:
    - master